### ISSUE TITLE
Are PRs being considered?

### ISSUE THREAD

**Issue by keshavramaswamy** [LeiG/Applied-Predictive-Modeling-with-Python#3]
Hi,
Thanks a lot for creating these notebooks. They are great!
I have a  PR to add a particular plot in one of the notebooks. Are they being considered?
Please let me know.
Regards,
Keshav

**Comment by LeiG** [comment]
Thanks!

Feel free to submit a PR if you want to improve upon the current version.

**Comment by keshavramaswamy** [comment]
Thanks - will submit one!
